[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['solady/=lib/solady/src/']
solc = "0.8.24"

# solc_version...
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
